version: '3.3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cherifuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'cherifdv'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'cherifdvroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume: